FROM mysql

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=url_shortening_service

# Exponer el puerto 3306 para que sea accesible desde localhost
EXPOSE 3306

# Definir un volumen para los datos de MySQL
VOLUME /var/lib/mysql
